/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaHamburger.view.MainView', {
    extend: 'Ext.Container',
    alias: 'widget.mainview',

    requires: [
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        cls: 'hamburger-content-overlay',
        itemId: 'MainView',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Sencha Hamburger',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'hamburgerBtn',
                        text: '<i class="fa fa-bars"></i>'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onHamburgerBtnTap',
                event: 'tap',
                delegate: '#hamburgerBtn'
            }
        ]
    },

    onHamburgerBtnTap: function(button, e, eOpts) {
        this.openHamburgerMenu();
    },

    openHamburgerMenu: function() {
        this.removeCls('in');
        this.addCls('out');
        Ext.ComponentQuery.query('#hamburgerMask')[0].show();
    },

    closeHamburgerMenu: function() {
        if(!this.element.hasCls('out')){
            return;
        }
        this.removeCls('out');
        this.addCls('in');
        Ext.ComponentQuery.query('#hamburgerMask')[0].hide();
    },

    menuOptionSelected: function(record) {
        this.closeHamburgerMenu();
    }

});