/*
 * File: app/view/HamburgerMenu.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaHamburger.view.HamburgerMenu', {
    extend: 'Ext.Container',
    alias: 'widget.hamburgermenu',

    requires: [
        'Ext.Img',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'hamburger-content-menu',
        itemId: 'HamburgerMenu',
        layout: 'fit',
        items: [
            {
                xtype: 'container',
                cls: 'blur-container',
                itemId: 'blurBackground',
                items: [
                    {
                        xtype: 'image',
                        cls: 'blur',
                        src: 'https://download.unsplash.com/photo-1425136738262-212551713a58'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'menu-content',
                itemId: 'menuContent',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'image',
                        cls: 'menu-face',
                        src: 'https://download.unsplash.com/photo-1416400453940-65c69d70ad91'
                    },
                    {
                        xtype: 'container',
                        cls: 'menu-name',
                        html: 'The Bird',
                        itemId: 'menuName'
                    },
                    {
                        xtype: 'list',
                        scrollable: false,
                        cls: 'menu-list',
                        height: 600,
                        itemId: 'mylist',
                        style: {
                            overflow: 'visable'
                        },
                        itemTpl: [
                            '<div><span class="fa-stack fa-lg">',
                            '  <i class="fa fa-circle fa-stack-2x" style="color:rgba(0,0,0,0.1);"></i>',
                            '  <i class="fa fa-{icon} fa-stack-1x"></i>',
                            '</span> {text}</div>'
                        ],
                        store: 'MenuStore'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMylistItemTap',
                event: 'itemtap',
                delegate: '#mylist'
            }
        ]
    },

    onMylistItemTap: function(dataview, index, target, record, e, eOpts) {
        dataview.deselectAll();
        Ext.ComponentQuery.query("#MainView")[0].menuOptionSelected(record);
    }

});